sources/PTYTextView.m

Not sure if this was an intentional design decision, but having a transparent cursor can be a bit distracting when content bleeds through it. The text doesn't use transparency, so I figured the cursor should be the same.
Here's an animation showing the change:

Make cursor opaque

---

sources/VT100CSIParser.m
sources/VT100StringParser.h
sources/VT100StringParser.m

I found out that this change is still in `fixKoreanEncodings` branch.
I've compiled and checked that it works with CP949 encodings well.
Is there any further progress required to merge this into master branch?

Fix korean encodings

---

ThirdParty/PSMTabBarControl/source/PSMTabBarControl.m

When using the "[LSUIElement hack](https://code.google.com/p/iterm2/issues/detail?id=954)" to hide dock icon, the menu bar also disappears, leaving users with no way to reach the main menu.

Show main menu when right clicking empty tabBar region

---

sources/TaskNotifier.m

Pids are added to a "deadpool" in TaskNotifier when we expect them to
die soon. When reaping processes, it's possible that waitpid() will
return 0, meaning that the process is not yet dead. In that case, put
its pid back into the deadpool so that we attempt to reap it again.
Otherwise the process will become a zombie.
Fixes https://code.google.com/p/iterm2/issues/detail?id=3471

Don't forget about processes that were alive when we tried to reap them

---

sources/iTermSemanticHistoryController.m
sources/iTermSemanticHistoryPrefsController.m

Without this, if a user has both BBEdit and TextMate installed and
chooses BBEdit as default for semantic history, iTerm2 would still
launch TextMate. This is because both were configured to use the
same URL scheme.
using that has the problem that when both BBEdit
(Also fix a typo in a debug message :)
Note: Unfortunately, I am unable to build iTerm2, so this has *not* been verified to work -- things, is, on my OS X 10.8.5 machine, ibtoold segfaults (on NumberOfSpacesAccessoryView.xib, I think). Still, this fix should be correct, I hope. I'll be happy to test a nightly build with this, or a custom test binary if somebody is willing to provide one.
Thanks for making iTerm2!

Fix for setting BBEdit as default for semantic history

---

sources/iTermSemanticHistoryController.m
sources/iTermSemanticHistoryPrefsController.m

Reverts gnachman/iTerm2#206 - x-bbedit doesn't actually open files (documented here: https://groups.google.com/forum/#!topic/bbedit/9sjczMsPO1g)

Revert "Fix for setting BBEdit as default for semantic history"

---

sources/FindViewController.m

More aggressive fix for issue 3496. The original fix allowed
a possibility for enqueued events to be processed before
the text field gained focus, so that for example typing
cmd-F followed by 'a', the 'a' would go to the iTerm window.
This fix ensures that enqueued events go to the search field.

Make the find bar first responder immediately upon opening

---

sources/PTYTextView.m

This makes no substantive difference to the calculation, but is likely what was intended.

take midpoint of min/max when estimating points for badge text font

---

iTerm2.sdef
sources/PTYSession+Scripting.m

I've completely replaced the old notion of not sending a newline if the text ends in a space.
I think this works, but I'm currently unable to see how to use Applescript with iTerm2 v3.
With iTerm2 v2, I could do something like:
set term to (make new terminal)
tell term
set sess to (launch session "default")
end tell
tell sess to write text "echo"
With iTerm2 v3, I simply don't see how to get a handle on a session, new or old, to use `write` with.
As such, I cannot test my changes. If you let me know how to get a session handle, I'll be happy to test and fix, if needed.

Add "with/without newline" argument to Applescript write verb

---

tests/imgcat

This gives better help for the command (e.g. it understands `--help`).
I just thought I'd apply one of my favorite patterns for `sh` scripts.

imgcat: put in a posix sh getopt pattern

---

sources/PseudoTerminal.m
sources/SolidColorView.m
sources/iTermRootTerminalView.h
sources/iTermRootTerminalView.m

Titlebar separator is now slightly lighter in color, and adjusts itself when the window is in the background.
It's a small change, but it's a lot nicer this way.

Fixed titlebar separator

---

sources/iTermRule.m

- the colon from user@host:path has been included in the hostname
- user@host has not been recognized

Fix pattern matching for user@host and user@host:path

---

sources/PTYScrollView.m

This makes the scrolling behavior a bit nicer so it doesn't effectively ignore small scroll events. It matches the behavior of Terminal.app a bit better in this regard.

Make small scroll events move the terminal by one line.

---

iTerm2XCTests/iTermRuleTest.m
sources/PTYSession.m
sources/iTermRule.m

This adds in the ability to only specify part of the full hostname for APS. For example instead of having to add:
someservice01.stage.company.com
someservice02.stage.company.com
someservice03.stage.company.com
otherservice01.stage.company.com
otherservice02.stage.company.com
you can just add:
.stage.company.com
and for prod:
.prod.company.com
In my use case I wanted two ssh profiles, one for stage servers and one for production and didn't want to have to type in over 50 server names into each.
I left exact match in place to take precedence over a partial match.

Allow substring hostname matching.

---

Interfaces/PreferencePanel.xib

While using iTerm I noticed that the wording was a little odd for the triple click setting.
It originally said "Triple-click selects full wrapped lines" but perhaps something like "Triple-click selects entire wrapped lines" would be clearer. 
Hope this isn't too much of a nitpick!

Fixed wording in settings for triple-click setting.

---

badge_evolution.md
sources/iTermAdvancedSettingsModel.h
sources/iTermAdvancedSettingsModel.m
sources/iTermBadgeLabel.m
sources/iTermTextDrawingHelper.m

This leaves the current method of creating and drawing a badge untouched, but simply exposes all the numbers (and the font) in the Advanced Preferences. So it is still pinned to the top right corner.
See the file `badge_evolution.md` for my ideas on a roadmap for further enhancing badges.
relevant:
[New configuration settings: badge location, font and size. (#3508)](https://gitlab.com/gnachman/iterm2/issues/3508)
[Add tmux-like status line (#2941)](https://gitlab.com/gnachman/iterm2/issues/2941)

Configureable badge size, font, & margins

---

sources/NSBezierPath+iTerm.m

We were over-shooting the initial find view bezier curve drawing, making
the curve->line->curve paths discontinuous on both sides.
In the animation, this would appear as 2 jagged triangles on both side of the find view,
whenever the view's height was smaller than 2*radius of the bezier curve.

Fix find view invocation/dismissal animation

---

sources/FindViewController.m
sources/HotkeyWindowController.m
sources/PTYTextView.m
sources/iTermController.m

**Use dispatch_once for one-shot actions**
Unless there's a specific reason not to use this (for perf, if all static variable accesses are guaranteed to
occur on the main thread), dispatch_once is usually a cleaner pattern.
**focus ring drawing**
this is something that has always irked me in AppKit. The focus ring is appearing above the title bar when sliding down, even though the search field is behind that bar.
**Align static path strings**
some variable definition alignment
**Refactor system version check code**
refactored duplicate code

Focus ring drawing fix, and some code refactoring

---

sources/iTermAdvancedSettingsViewController.m

This property is accessed multiple times per table view reload. We were unnecessarily
recomputing the same value hundreds of times.
This patch also caches a global sorted settings, as this value is constant and is accessed multiple times.
Advanced tab load time decreased dramatically.

Cache filtered advanced settings

---

iTerm2XCTests/iTermNSStringCategoryTest.m
iTerm2XCTests/iTermSemanticHistoryTest.m
sources/NSStringITerm.h
sources/NSStringITerm.m
sources/iTermSemanticHistoryController.m

The main motivation for this change is that git when presenting merge conflicts sometimes shows the file paths in single quotes. Instead of just adding single quotes, I thought it was just as well to add some other delimiters that are unlikely to appear in file names

Strip more bracketed delimiters

---

sources/iTermApplicationDelegate.m
sources/iTermController.h

for directories, this fix aims to launch to prefill the bookmark dict with a custom working directory, instead
of launching it with the default working dir, and then manually running "cd $NEW_DIR;\n"
for executable files, the bookmark dict is filled with an initial text value
Note: dragging and dropping a shell script that does "echo 'hello world'" results in
a broken pipe on my machine (with or without this fix)

dragging and dropping a dir or executable file on iTerm in Dock blocks app for 1 second

---

sources/iTermTipController.m

I noticed a small typo in the 'See Tips of the Day?' prompt.
old
> ...Tip of the Day message help you learn...
new
> ...Tip of the Day message to help you learn...

Fix typo in 'See Tips of the Day?' prompt

---

sources/NSEvent+iTerm.m

iTerm2 mimics MacOS's Terminal and produces "\" instead "¥", when the yen button of a Japanese keyboard is pressed. This is because of a legacy quirk of Japanese keyboard layouts, that use ¥ instead of \\.
However, the current implementation naively checks only if the pressed key is the yen key (the key code). However, as the user can change and edit keyboard layouts, the yen keys doesn't necessarily produce "¥".
With this commit, it checks whether the character production of the key is "¥". It still needs to check the keycode in order to prevent any other mappings that produce "¥" from turning "\". (Another solution would be to check if the `charactersIgnoringModifiers` equals to "¥" and leave out the key code check... I'm not aware which one has less corner cases.)

Fixed the yen button error that happened if the current keyboard layout doesn't produce "¥".

---

sources/NSEvent+iTerm.m

I came up with another corner case. Thanks, #showerthoughts.
It now checks that the production that would be emitted originally by the keypress would be "¥" also – this for the (rare) case that alt + ¥ would produce something special that the user intended to produce.
In the normal case (the standard Japanese keyboard on Mac) alt + ¥ is mapped to emit "\", so in the majority of cases "\" will be emitted either way.

Fixed yet another cornercase with the "¥".

---

Interfaces/PreferencePanel.xib

The tooltip otherwise reads:
For this setting to take effect you must disable "Native full scren windows"

Fixes a typo 'screen' not 'scren'

---

sources/iTermSemanticHistoryPrefsController.m

Since TextMate has been released as a release candidate it has changed
the bundle identifier and removed the ".preview" suffix [1].
Not sure if we should keep TextMate 1 or not, but I kept it for now.
[1] https://github.com/textmate/textmate/commit/204c735079d01a5bcc43923756827a26a3fbf107

Update bundle identifier for TextMate

---

tests/catch.c

Signal handlers might be called repeatedly. As such they can't call
non-async-safe functions such as printf. Instead set a sentinel and
check for it.

Fix bug with signal handling in catch.c

---

ThirdParty/AMIndeterminateProgressIndicator/AMIndeterminateProgressIndicator.m

The activity spinner in iTerm would look pretty different then in most other apps: a segment would start very light and become darker and darker instead of starting dark and fading out. This diff reverses the fading effect.
Before:
After:

fix activity indicator in the tabbar

---

Interfaces/PreferencePanel.xib

Fixed a typo that saw in popup message for the "Minimum contrast" slider. The mistyped word I found was "whtie".

Fixed typo in "Minimum contrast" slider.

---

Interfaces/iTermPasteSpecialWindow.xib

The `Paste` button in the special paste window was not properly aligned.
Before:
After:

Fix position of 'Paste' button

---

Interfaces/MainMenu.xib
sources/iTermApplicationDelegate.m

If you don't restart iTerm for a long time you can miss updates. This is typically solved by using the option in the "iTerm" menu. However if you have the "Exclude from Dock and ⌘-Tab Application Switcher" option enabled, there is no easy way to check for updates without disabling this option or restarting iTerm.
This pull request adds an option to the menu bar icon to trigger the "Check for Updates" functionality.

Add "check for updates" to menubar icon

---

plists/SmartSelectionRules.plist

This allows URLs such as http://sharedserver.com/~homedir/index.html to be parsed and opened correctly.
I've updated my own profile preferences, but I feel like people would benefit from having this as the default.

Allow ~ in HTTP URL paths

---

sources/iTermPasswordManagerWindowController.m

Every time I re-open my compiled iTerm2, it requires re-authentication (Touch ID). Is that because I disabled code-signing? So I wasn't able to test the case when iTerm2 is first opened, but doesn't require authentication.

Auto select the account in the password manager after auth.

---

sources/iTermInitialDirectory.h

On a case-sensitive file system iTerm2 fails to build because of missing Profile.h. I believe this is a typo, and actually ProfileModel.h is meant (and iTerm2 builds successfully then).
The build succeeds on case-insensitive file systems, because ProfileModel.h is pulled via ITAddressBookMgr.h, and Profile.h resolves to the system header profile.h (note the small letter p).

Fix build failure on case-sensitive file systems

---

sources/PTYTab.m
sources/iTermAdvancedSettingsModel.h
sources/iTermAdvancedSettingsModel.m

Currently the directional focus hotkeys will wrap, focusing a view on the opposite side of the window.
Personally I find this very confusing and often end up in situations whereby I have no idea where focus has gone, (mostly because I've come from a tiling window manager that behaved slightly differently).
This commit adds an advanced option (probably not important enough to be a real option) that prevents such wrapping.

Add advanced setting preventing directional focus from wrapping

---

sources/iTermPowerManager.m

- Fixes singleton implementation of the power manager instance (bug #6550)
- Changes the way power status is monitored to a more optimal callback
when power source has been changed to a limited power source
(IOPSCreateLimitedPowerNotification)
ps. excuse my objc, it's a little bit rusty. :)

Fixes singleton, refactor power monitoring mode (#6550)

---

iTerm2.xcodeproj/project.pbxproj
sources/GrowlTrigger.m
sources/PTYSession.h
sources/PTYSession.m
sources/PTYTab.m
sources/PTYTask.m
sources/PseudoTerminal.m
sources/TransferrableFile.m
sources/VT100Screen.h
sources/VT100Screen.m
sources/iTermAdvancedSettingsModel.h
sources/iTermAdvancedSettingsModel.m
sources/iTermController.m
sources/iTermNotificationController.h
sources/iTermNotificationController.m

After the introduction of the built-in notification system in Mountain Lion (10.8) Growl has been falling into disuse. The 2.0 framework supports the native `NSUserNotificationCenter` and acts as a bridge, which iTerm is still using to send notifications. Considering iTerm2 was made for 10.10+, Growl is in fact acting as a forward service only in most of the cases (except for users who still prefer to install and use Growl).
The main problem with using Growl as a forwarding service is the lack of customization. The framework hasn't been updated for a long time, meaning iTerm is stuck with the frozen notification format implemented by Growl. Forwarded notifications don't have a sound, for example. Even though `NSUserNotificationCenter` supports it, Growl does not use it. Nor implements …

Native Notifications

---

sources/iTermAdvancedSettingsModel.m

The banner message displayed is “Session Contents Restored”.

Fix the showSessionRestoredBanner description.

---

sources/VT100Screen.m

Previously when:
1. Move the cursor to the right
2. A command occupies more than one line, the cursor is at the second column and second line, and move the cursor 1 column left
The command range became incorrect, and "Select Current Commands" would select a wrong range.
Calling `-screenCommandDidChangeWithRange:` in `-terminalCursorRight:` fixes (1), `-terminalCarriageReturn:` fixes (2).
I'm not sure it's necessary in other methods, but they seem to be related.

Update the command range when the cursor moves.

---

sources/iTermAdvancedSettingsModel.m

Fix typo.
This is also known as **thethe** terminfo E3 capability -> This is also known as **the** terminfo E3 capability

Fix typo in Advanced Settings

---

sources/iTermAdvancedSettingsModel.h
sources/iTermAdvancedSettingsModel.m
sources/iTermController.m

Hi there. I am far from an expert, so please let me know if you want me to make any changes.
I've been using this modification for months, and I figured it is time that I tried to contribute it upstream.
I have a chrome extension that adds ssh:// links to the AWS console, but the only problem is that I have to add extra options, such as ProxyJump, because the servers are not accessible without tunneling through another host first.
So to accomplish this, I made iTerm run a shell script, which parses the arguments, and adds more arguments in turn. It then runs the standard ssh binary.
My shell script:
```shell
#!/bin/bash -e
extra_args=()
for arg in "$@"; do
if [[ "$arg" == *".example.com" ]]; then
extra_args+=("-J")
extra_args+=("bastion.example.com")
fi
done
echo ssh "${extra_args[@]}" …
```

Add advanced option to customize path to ssh for ssh:// links

---

sources/iTermScrollAccumulator.m

Hi, I propose to fix issue 6982 this way. Here's my thoughts:
First, it seems to me that line 107 is unnecessary and causing problems. I don't think you need to bump up remaining delta at end of scroll. If the remaining delta was opposite to the scroll direction, it can cause scroll back. So this seems like the original cause of the issue.
Second, rounding `_accumulatedDeltaY` and having a possibility that `_accumulatedDeltaY` can be opposite to the actual moving direction makes the code hard to understand intuitively, imo. 
If you think it is necessary to make the initial move easier to trigger, there should be other ways to do so.
How do you think?

Fix scroll-back in another way. Issue 6982

---

sources/iTermRootTerminalView.m
sources/iTermStandardWindowButtonsView.h
sources/iTermStandardWindowButtonsView.m

Thank you for making this awesome emulator, been using it since I first got my mac and could not imagine working without it! Also thanks for implementing the compact mode which looks real nice 🙂
This PR fixes on of the bugs with manual placement of the stoplight buttons, on macOS you can press and hold the option key to zoom instead of going fullscreen. This PR reimplements that functionality for the custom buttons.
Demo:
First window: TextEditor
Second window: iTerm2 compiled from ```master```
Third window: iTerm2 compiled from this branch with the fix applied

Support option key for zoom button in compact mode

---

sources/Metal/Renderers/iTermHighlightRowRenderer.mm

When using GPU rendering and the window height is not divisible by the character height (eg. by ctrl-dragging window's borders) the mark highlight is rendered out of place.
Here's a demonstration of this issue:
On the left is iTerm 3.2.5 and on the right is my fork

Wrong frame position in highlighted mark (when rendering with Metal)

---

sources/iTermFindDriver.h

I have a case-sensitive filesystem. The build was failing saying that it couldn't find `cocoa/cocoa.h` here. Changing the path to `Cocoa/Cocoa.h` seems to have fixed it.

use case-sensitive path for Cocoa

---

plists/PresetKeyMappings.plist

This PR changes the "Terminal.app Compatibility" keyboard mapping to map "⌥←" and "⌥→" to "Escape"+`b` and "Escape"+`f`, respectively, which (for me at least...?) correctly implements the word-jumping functionality in Terminal.app. Seems to work with all shells. I've been manually doing this myself for several years. And I think I saw an open issue on GitLab somewhere about this... perhaps [#2587](https://gitlab.com/gnachman/iterm2/issues/2587), although I'm only fixing the 'option' bits, as 'command' left and right are not implemented in Terminal.app.
---

Correct "Terminal.app Compatibility" keyboard mapping "⌥←" and "⌥→"

---

api/library/python/iterm2/iterm2/window.py

These 2 methods take a `profile` param which is a string (or None).
I'm pretty sure the intention here was to access the profile module.

use profile module, not profile name string

---

sources/iTermController.m
sources/shell_launcher.c

Move iTerm-server daemon to per-user namespace. Issue 4147

---

api/library/python/iterm2/iterm2/connection.py
sources/iTermRootTerminalView.m

- Add the optional parameter `debug` to the methods below.
- `run_until_complete()`
- `run_forever()`
- `Connection().run()`
- Defaults to disabled if unspecified when calling the above methods.
- Fixes https://gitlab.com/gnachman/iterm2/issues/7785
Signed-off-by: Ricky Grassmuck <rigrassm@gmail.com>

Add ability to enable/disable Asyncio debug mode

---

sources/iterm2_git_poll.sh

* use `/usr/bin/env sh` for the shebang to allow a user's environment to dictate which `sh` is run
* use locals to avoid leaking function variables
* use lowercase names for locals
* convert `~` in the received directory path to the user's `$HOME` directory
* use the more portable and clearer `test` conditional by using `[ ... ]` notation instead of the arithmetic expression `(( ... ))`
* use `command` to locate the `git` binary

iterm2_git_poll.sh tweaks

---

sources/ToolDirectoriesView.m

This fixes a crash on macOS Catalina.

Don't release the system bold font

---

api/library/python/iterm2/iterm2/session.py

As described in:
proto/api.proto:597

Session.async_set_variable(): Document required `user.` variable prefix

---

sources/TmuxController.h
sources/TmuxController.m
sources/TmuxDashboardController.m
sources/TmuxSessionsTable.h
sources/TmuxSessionsTable.m

The tmux dashboard allows linking windows between different sessions
via drag-and-drop. This change modifies that behaviour, such that if
option or cmd are pressed during the drag, the window will be moved
instead of linked.

Allow moving tmux windows between sessions by holding option/command

---

api/library/python/iterm2/iterm2/util.py

**Why**:
Python type annotations is wrong for Size and Point.
Traceback:
```
8/24, 11:23:59.003 AM: Traceback (most recent call last):
8/24, 11:23:59.003 AM:   File "/Users/dmitryvasilishin/Library/ApplicationSupport/iTerm2/Scripts/iterm2-kube/iterm2env/versions/3.7.2/lib/python3.7/site-packages/iterm2/registration.py", line 23, in generic_handle_rpc
8/24, 11:23:59.003 AM:     result = await coro(**params)
8/24, 11:23:59.003 AM:   File "/Users/dmitryvasilishin/Library/ApplicationSupport/iTerm2/Scripts/iterm2-kube/iterm2env/versions/3.7.2/lib/python3.7/site-packages/iterm2/statusbar.py", line 262, in handle_rpc
8/24, 11:23:59.003 AM:     await onclick(session_id)
8/24, 11:23:59.003 AM:   File "/Users/dmitryvasilishin/Library/ApplicationSupport/iTerm2/Scripts/iterm2-kube/iterm2-kube/iterm2-k …
```

[Py] Fix type annotations for Size and Point

---

sources/iTermActionsModel.m

In `iTermActionsDidChangeNotification`, use `[self initPrivate]` instead of
`[self init]`, which is marked `NS_UNAVAILABLE` in `iTermBaseNotification`.
Fixes build with newer clang versions.

iTermActionsDidChangeNotification: use initPrivate

---

Interfaces/PreferencePanel.xib

I've been looking at the Appearance section in the Preferences today, and I noticed some elements were badly positioned, which triggered my OCD so badly I needed to make this PR 😉 
This fixes:
- the "Theme:" label being vertically positioned one pixel differently than the other two
- the "Show window number in title bar:" checkbox/label being offset one pixel to the right
- some checkboxes in the stacks having different vertical offsets from each other (now all the spaces should be equal to 6px)
BTW, it looks like you guys might have to switch to AutoLayout in the end, because Xcode 11 seems to just turn it on without any way to turn it off… 😅

Fix some unevenly arranged elements in Appearance preferences

---

sources/VT100Screen.m

When I run longcat (https://github.com/mattn/longcat) on iTerm2 with option
"-H -n N" with large integer N, the image is not shown.
The debug log says:
```
1569935975.044434 VT100Screen.m:3950 (-[VT100Screen appendImageAtCursorWithName:width:units:height:units:preserveAspectRatio:roundUp:inset:image:data:]): Append 0 rows of image characters with 80 columns. The value of c.image is 1
```
There is a problem in scaling process that can make width (or height) zero.
I've confirmed the problem is fixed by 5c0ecac and the image is shown.

Prevent images from disappearing due to scaling

---

iTerm2.xcodeproj/project.pbxproj
iTerm2.xcodeproj/xcshareddata/xcschemes/iTerm2.xcscheme

Added SSKeychain as a dependency to the iTerm2Shared target, thus allowing `xcodebuild -project iTerm2.xcodeproj` to successfully build iTerm2.app from the command line without a `can't locate file for: -lSSKeychain` error being generated.

Fixed xcodebuild

---

Makefile

[Nix](https://nixos.org/nix/) has its default home directory under `/private/var/empty`. As a result, Xcode sets the build directory relative to this home directory. Since Mojave the user has no write permission in that directory and the build fails.
Set the build directory to a path where Nix has write permission. This is done with the 
`-derivedDataPath` flag to `xcodebuild`.
- I also updated the path where the executable lies.
Before: `build/Deployment`
New: `Build/Products/Deployment`
You may want to change them for the other Makefile flags as well.
- Added empty `CODE_SIGN_IDENTITY`and `DEVELOPMENT_TEAM` to fix codesign issue.
- macOS Catalina 10.15
- Xcode 11.1

Add Nixpkgs-specific make flag to fix build with nix

---

sources/iTermEditKeyActionWindowController.m

Fixes a bug in the "Keys" menu, where assigning a keybinding to "Increase Height" instead assigns to "Decrease Height" — looks like this was [introduced](https://github.com/gnachman/iTerm2/commit/2a58778cb62c8318ba003f8991fcdeab122cedbc#diff-d685851ee8f00202cb41d7229dba8234R135) as part of a refactoring a couple weeks ago.
Screengrab demonstrating issue:

fix(keys): Correctly map 'increase height' shortcut.

---

sources/PseudoTerminal.m
sources/iTermAdvancedSettingsModel.h
sources/iTermAdvancedSettingsModel.m
sources/iTermApplicationDelegate.m
sources/iTermController.m

Hi,
This is a prototype to only apply the 'exclude from app switcher' setting when all windows are hotkey windows. Why?
I have two modes of operation for iTerm:
1. To quickly enter transient commands.
2. For long lived vim/ssh/log sessions.
Hotkey windows are ideally suited for the first case, and standard windows are great for the second. The pedant in me dislikes having iTerm appear in the app switcher when I only have a hotkey window open, but having iTerm in the app switcher is required for the second use case. I want the best of both worlds, so I implemented this prototype PR to achieve that:
**iTerm2 excluded from app switcher when only a hotkey window is open:**
**iTerm2 included in app switcher when a non-hotkey window is open:**
I labeled this prototype because I am not …

Only apply 'exclude from app switcher' setting when all windows are hotkey windows

---

sources/iTermSemanticHistoryController.m

This fixes wrong encoding of paths when cmd-clicking on existing files
in sematic history to for example open the file in MacVim or a custom
URL.
The problem is that URLHostAllowedCharacterSet does not contain the
slash character, so eg. /Users/foo/bar baz.txt is encoded as
%2FUsers%2Ffoo%2Fbar%20baz.txt instead of the correct
/Users/foo/bar%20baz.txt.
While some application might not care this at least breaks opening files
in MacVim, which requires proper path encoding.
This changes to use the correct URLPathAllowedCharacterSet instead.
It is possible that URLHostAllowedCharacterSet contained "/" in the past,
even though it is not a valid character for the host part of a URL and
Apple fixed it it newer SDK versions.
This fixes issue [#8994 – Wrong URL Encoding for files opened via …

Fix wrong URL encoding for sematic history paths

---

sources/iTermPasteHelper.m

The newlines will be removed when sanitizing.

Do not warn multi line paste when the RemovingNewLines flag is true.

---

sources/iTermTextViewContextMenuHelper.m

When the terminal context menu is opened from a session titlebar, the coordinates passed to `menuAtCoord:(VT100GridCoord)coord` are (-1,-1), of which the y-coordinate is used as an array index to extract a line from the terminal grid in order to extract a URL. This causes a crash due to a `[-1]` array index downstream in `getLineAtIndex:(int)theIndex` as the context menu is being built when left-clicking the session titlebar context menu button in all versions after 2534252ebfada543237ea6d6ee9bf47dabe15579 with the following message:
```
Performing @selector(openMenu:) from sender NSButton 0x600001e6c4d0
Assertion failed: (NO), function -[VT100Screen getLineAtIndex:withBuffer:],
file /Users/.../iTerm2/sources/VT100Screen.m, line 1804.
```
This PR adds a lower bounds check on the …

Don't attempt to extract a URL from invalid coordinates (-1,-1)

---

sources/PseudoTerminal.m

When changing window styles using `Window > Window Style`, the window's blur setting is temporarily lost until the window regains focus. This re-enables the blur after modifying the window style.

Recheck blur when changing window styles

---

sources/iTermDynamicProfileManager.m

**Note well: this may not be the optimal way to do this, and I may have missed other spots that enumerate directory contents.**
GNU tools often support or default to making backups of modified files. By default, the previous contents of the file are preserved in `filename~` or `filename.~1~`. See [the coreutils docs](https://www.gnu.org/software/coreutils/manual/html_node/Backup-options.html) and [some Emacs docs](https://www.gnu.org/software/emacs/manual/html_node/emacs/Backup-Names.html). Note that Emacs produces `filename~` backups by default. Users generally do not expect these files to be read automatically.
When using Emacs to edit a dynamic profile, saving it immediately causes an iTerm diagnostic: both `filename` and `filename~` will likely contain the same UUID.
Instead of making …

Ignore dynamic profile files that end in "~" (GNU-syle backups)

---

sources/PseudoTerminal.m

When changing the tab bar theme in `Preferences > Appearance > Theme`, all active windows lose their blur until each window is clicked individually or regains focus. This re-enables blur after changing the tab bar theme.

Recheck blur when updating tab bar theme

---

.gitlab/issue_templates/Bug.md
.gitlab/issue_templates/Crash.md
.gitlab/issue_templates/Perfomance Issues.md

added three GitLab [description (issue) templates](https://docs.gitlab.com/ee/user/project/description_templates.html), for three different cases:
- Bug reports
- Crash report
- Perfomance issues
this could replace the default issue template and could clear up some confusion over what information is required by the reporter for each issue type.
it also automatically applies labels on issue creation. the labels would need to be created on the [project (gitlab.com/gnachman/iterm2) manually once](https://docs.gitlab.com/ee/user/project/labels.html#project-labels), though.
take it for a test drive over here 😉 : https://gitlab.com/niklasjanz/iterm2/-/issues/new
the templates can also be referenced in the URL directly, like so: https://gitlab.com/niklasjanz/iterm2/-/issues/new?issuable_template= …

provide gitlab description templates

---

ThirdParty/UKCrashReporter/UKCrashReporter.xib

Don't use justified text for crash log

---

sources/PreferencePanel.m

The search bar on iTerm preference pane has a hover background like normal toolbar items, which is slightly different from search bar seen on toolbars is other Apps like Finder.
After some time diving into is issue, the solution is quite simple, just exclude it from `toolbarSelectableItemIdentifiers`.
This pull request removes `searchFieldToolbarItem` from `toolbarSelectableItemIdentifiers` to make it non-selectable, thus removes the hover background. A `NSToolbarFlexibleSpaceItemIdentifier` is also added between other items and the search bar item to achieve proper layout on Big Sur.
Since this change may introduce compatibility issue with older systems. I've tested it on Big Sur 11.2, Catalina 10.15.7 & Mojave 10.14.6.
- On Big Sur 11.2
- On Catalina 10.15.7

 Fix preferences pane search bar style on Big Sur.

---

sources/PTYSplitView.m
sources/iTermMetalBufferPool.h
sources/iTermWindowHacks.m

iTerm will fail to build/crash at launch without these, so here are some very quick patches. Let me know if you would like these to be fixed in some other way.

Preliminary fixes for macOS Monterey

---

sources/PTYSession.m

We forgot to use weakSelf in the observer block, keeping the entire session (and all its lines) alive even after the window had closed.

Fix a PTYSession retain cycle

---

api/library/python/iterm2/iterm2/__init__.py
api/library/python/iterm2/iterm2/preferences.py

Hello, this merge request hopes to expose the `iterm2.rpc.async_set_preferences` call to Python.
I'm still learning how to actually compile & test this code, and am not generally familiar with OSX development, so it may take me a while to wrangle this into a validated state. I'm hoping this is still a useful PR in this state, untested as it is. It seeks to fix an issue I just opened for this, [gnachman/iterm2#9810](https://gitlab.com/gnachman/iterm2/-/issues/9810)
note, i have also not yet investigated what might be added for documentation, nor tests.

attempt to add async_set_preference

---

sources/Metal/Renderers/iTermCursorRenderer.m

The height of the vertical cursor does not change when line spacing < 1.
However, the height of the box cursor does change.
Trying to make them behave consistently.

Fix vertical cursor height

---

plists/beta-iTerm2.plist
plists/iTerm2.plist
plists/iTerm2ForAppleScriptTesting-Info.plist
plists/nightly-iTerm2.plist
plists/preview-iTerm2.plist
plists/release-iTerm2.plist

Command line programs that use CoreBluetooth will crash with SIGABRT if this is not included in info.plist. The message doesn't seem to actually be shown, but [CentralManager.didUpdateState:](https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/1518888-centralmanagerdidupdatestate?language=objc) will be called with the state set to [CBManagerStateUnauthorized](https://developer.apple.com/documentation/corebluetooth/cbmanagerstate/cbmanagerstateunauthorized?language=objc) unless the users enables Bluetooth permission in *System Preferences*.

Allow requesting Bluetooth permission

---

BetterFontPicker/BetterFontPicker.xcodeproj/project.pbxproj
SearchableComboListView/SearchableComboListView.xcodeproj/project.pbxproj

This allows for building the project with a newer Swift compiler than the one that was used to compile the binary dependencies that are in committed to the repository.
(This requires a rebuild of the frameworks, too; I trust you can take care of that.)

Set BUILD_LIBRARY_FOR_DISTRIBUTION for frameworks

---

sources/iTermTextViewContextMenuHelper.m

Hi!!
This code adds a translation from scientific notation to decimal format in the context menu.
I implemented this feature some time ago and at least for me it has proved to be very useful, so I think it might be useful for others as well.
Some examples:
`1e10` -> `1e3 = 1,000`
`.314E1` -> `.314E1 = 3.14`
`-314e-2` -> `-314e-2 = 3.14`
Screenshot:

Add scientific notation context menu synonym

---

sources/PTYSession.m
tools/updateVersion.py

1. macOS Monterey 12.3 removes python2.
2. Fix issue: https://gitlab.com/gnachman/iterm2/-/issues/10136#note_884250463

Using python3 on macOS 12.3 and fix null environment issue for tmux integration.

---

api/library/python/iterm2/iterm2/profile.py

I have documented this by trial and error, not sure it is correct.
Thought you should pass `None` to clear, but an empty string is what seems to work.
Have also made the description match type hinting.

Documents how to clear a background image

---

sources/SelectionExtraction.swift

I found that when I use **Edit -> Copy with Control Sequences** on `Build 3.5.20220828-nightly`, the resulting copied text has `\x1b[0` *without* a trailing `m` before newlines and at the end of the text.
I could definitely be confused here (ECMA-48 is a bit dense haha), but it *seemed* like the SGR sequences are required to end in the character `m` (aka `\x6d` aka 06/13). Specifically it says
> **8.3.117 SGR - SELECT GRAPHIC RENDITION**
> Notation: (Ps...)
> Representation: CSI Ps... 06/13
> Parameter default value: Ps = 0
If this is intentional (aka, there's some part of the spec I'm missing, which is more than likely) then we can just close this out.
Note: I had trouble getting this to build locally (kept failing with `No account for team "H7V7XYVQ7D"` despite changing it to `Sign to …

Fix SGR0 when using 'Copy with Control Sequences'

---

api/library/python/iterm2/docs/examples/settabcolor.rst
api/library/python/iterm2/docs/tutorial/running.rst
api/library/python/iterm2/iterm2/connection.py

In Python, I was naively passing the `ITERM_SESSION_ID` envvar into `app.get_session_by_id()` but not getting any sessions back. I then realized the env var is prefixed a window+tab+pane identifier which is not part of the session ID. I wasn't sure if this prefix always exists, so the example code regexes for the session id in a more flexible way than simply `.split(':')`.
I didn't see this mentioned anywhere, and couldn't find a great place to add it, so I just added it to the code sample on the example that I was basing my work on in the first place. I was hitting this because I was appending a tab color change to the end of long-running scripts, and the tab change would get applied to my CURRENT tab instead of the previous tab where I had left the long-running script running.
I also …

Small additions to settabcolor example and connection.py documentation

---

api/library/python/iterm2/iterm2/statusbar.py

This will allow static type checkers to not complain when it runs across code like this:
```python
python_mycomponent = StatusBarComponent(
...
knobs=[
CheckboxKnob("Debug", False, "mycomponent_debug"),
],
)
```

Python API: Making *Knob classes subclasses of Knob and moving Knob over to BaseKnob

---

sources/iTermSemanticHistoryController.m
sources/iTermSemanticHistoryPrefsController.h

The bundle identifiers for both VSCode and VSCode Insiders (beta builds) were already present but only the VSCode non-Insiders was used in the ⌘-click open logic. This adds the Insiders bundle ID to be handled the same way as standard VSCode.
Fixes [issue 11236](https://gitlab.com/gnachman/iterm2/-/issues/11236).

Add forgotten VSCode Insiders ⌘-click open handling

---

sources/VT100Terminal.m

Allow `xtermParseColorArgument` to accept four-digit hex values.

---

sources/PTYTextView.m
sources/iTermAdvancedSettingsModel.h
sources/iTermAdvancedSettingsModel.m
sources/iTermURLActionFactory.m

This adds an advanced setting which defaults to the current behaviour, but when switched off, disables the feature that Cmd-Click in a prompt opens the Command Info window. The Cmd-Click instead falls back to Smart Selection. The window can still be accessed via right click as normal.

Optionally disable Cmd-Click opening Command Info

---

sources/ProfilePreferencesViewController.m

This prevents the instances of `NSScrollView` under Preferences > Profiles (General, Terminal, Advanced) from being able to be horizontally elastically scrolled. This is achieved by subtracting the width of the scroll bar from the view.
This related code only prevents the animation:
`scrollView.horizontalScrollElasticity = NSScrollElasticityNone;`

Fix horizontal scrolling in preferences

---

sources/ProfilesGeneralPreferencesViewController.m

This typo isn't visible in the UI, but shows up when searching the preferences pane:

Fix typo in custom command `displayName`

---

Resources/shell_integration/iterm2_shell_integration.fish

Fixed string join in the `fish_prompt` function in the `iterm2_shell_integration.fish` shell script interpreting a dash character contained in the Fish prompt as a command option.
When the Fish prompt returned by the function `iterm2_fish_prompt` contains a dash character, the command `string join "\n" (iterm2_fish_prompt)` interprets it as a command option. Therefore it sets an unexpected option or fails with an error like the following:
```
string join: -----: unknown option
~/.shell/iterm2_shell_integration.fish (line 1):
string join "\n" (iterm2_fish_prompt)
^
in command substitution
called on line 93 of file ~/.shell/iterm2_shell_integration.fish
in function 'fish_prompt'
in command substitution
```
Added the "end of options" option (`--`) to the `string join` command just before the …

Fix dash in fish_prompt in iterm2_shell_integration.fish

---

api/library/python/iterm2/docs/examples/current_preset.rst
sources/iTermEditKeyActionWindowController.m
sources/iTermOpenQuicklyModel.m

Two changes are to comments, but the others appear in Settings/Shortcuts when you add an action and select 'Alert on Next Mark'. "session" is misspelled "sesssion".

Correct misspelling of 'session'

---

api/library/python/iterm2/docs/examples/enable_broadcasting.rst

The example was missing the required first arg, "connection".

Fix async_set_broadcast_domains example

---

sources/iTermMetalPerFrameState.m

This commit fixes a leak in metalGetGlyphKeysData due to the `positions` vector, which is always allocated, only being freed when the `bidiInfo` argument is not null. The fix is to always free the `positions` vector.
https://gitlab.com/gnachman/iterm2/-/issues/12029

Fix memory leak in metalGetGlyphKeysData

---

api/library/python/iterm2/docs/examples/index.rst

This PR fixes the line break in the Python Examples doc. Please see below:

fix: Python examples doc line break
