gnachman/iTerm2

sources/NSColor+iTerm.m
This is a continuation of #176.
=> Handle the xterm 256 colors as sRGB values

Interfaces/MainMenu.xib
Maybe I'm too picky but most apps use "Check For Update**s**..." :)
=> Fixed the plural form in "Check For Update..."

sources/iTermExpose.m
See https://gitlab.com/gnachman/iterm2/issues/3724
=> added check for hotkeywindow before setting alphavalues

sources/iTermTipData.m
=> fix(tip): small typo (matchine -> matching)

tests/imgls
Currently the imgls script spews lots of errors and even shows some files more than once when dealing with directories etc. This PR is supposed to fix that.
=> Make imgls handle non-files well

sources/PTYSession.m
This leads to a much nicer user experience. I type reasonably quickly and have a high key repeat rate and I'm frequently bothered by the perceived input latency.
=> Increases active window refresh rate to 60Hz

tests/download.sh
Hello.
Thanks for the great app.
=> download.sh fix and small improvement

sources/PseudoTerminal.m
Fixes issue [5375][0].
[0]: https://gitlab.com/gnachman/iterm2/issues/5375
=> Focus the right session in `didSelectTabViewItem`.

iTerm2.xcodeproj/project.pbxproj, plists/iTerm2.plist, sources/ServiceProvider.h, sources/ServiceProvider.m, sources/iTermApplicationDelegate.m
I have add Finder Services.But i do not know how to invoke your "new tab or new window" method.
Thanks.
=> add: support Finder Services

api/examples/python/README.md, api/examples/python/it2api, api/examples/python/iterm2.py
Also stop recommending that people run pip as root and instead just use
virtualenv.
=> Reduce the amount of amount of python2

sources/iTermAdvancedSettingsModel.m
This is a minor typo in the advanced prefs UI
=> Fix a minor typo

plists/ColorPresets.plist
This fixes the solarized dark background being slightly darker in iterm.
I also ran the same script to generate the colors for solarized light,
although I didn't check before if the colors were incorrect.
This changes solarized colors to use sRGB. The colors are calculated by
dividing the reference RGB values by 255.0 in ruby.
It might be a good idea for someone to run one more sanity test before merging. These are a lot of numbers and scripting, but I think I got it right.
As discussed here: https://gitlab.com/gnachman/iterm2/issues/3989#note_47289852
These are the reference colors used:
```
SOLARIZED HEX     16/8 TERMCOL  XTERM/HEX   L*A*B      RGB         HSB
--------- ------- ---- -------  ----------- ---------- ----------- -----------
base03    #002b36  8/4 brblack  234 #1c1c1c 15 …
```
=> Fix solarized colors

sources/iTermApplicationDelegate.m
Nothing more, nothing less. Just a few typo fixes.
The "disconnected from power" reason may be a bit long in terms of line length but I don't exactly know how to concatenate strings in Objective-C, or if you're even able to concatenate strings.
**EDIT:** Concatenated the "disconnected from power" reason. If my changes to it don't fit the normal code style though, I can always revert the commit.
=> Fixed some typos with the GPU Renderer Unavailability reasoning.

sources/ProfilesGeneralPreferencesViewController.m
=> Fixed "customc" typo

sources/PTYSession.m
This message confused me a bit the first time as it wasn't obvious which section of Preferences this would be on. This would make it easier for anyone to find it.
=> Specify preferences section

ThirdParty/hyper-tab-icons-plus/graphic_icons.json
Here is some more process names for Docker, npm, PHP, Python and compression apps.
=> More process icons

sources/iTermAdvancedSettingsModel.h, sources/iTermAdvancedSettingsModel.m, sources/iTermApplicationDelegate.m
I find I always want the profile menu to open in a new window, so added an advanced option to swap to this behaviour, instead of having to press option each time.
=> Add a preference to allow Profiles menu to open in new windows by default

Interfaces/PreferencePanel.xib, sources/ITAddressBookMgr.h, sources/ITAddressBookMgr.m, sources/PseudoTerminal.m, sources/PseudoTerminalRestorer.m, sources/iTermProfileHotKey.m
I like to have some tmux windows always maximize on open to the correct screen size, but I don't want to use the actual fullscreen options which also cover the dock.
=> Add a "Maximized" window type that is always maximized

sources/FutureMethods.m, sources/ITAddressBookMgr.m, sources/iTermAPIScriptLauncher.m, sources/iTermDynamicProfileManager.m, sources/iTermPreferences.h, sources/iTermPreferences.m, sources/iTermSessionFactory.m
A baby step towards an embeddable iTerm2 library -- some import clean-up
=> Some import clean-up

plists/iTerm2.plist
Fixes [#8392](https://gitlab.com/gnachman/iterm2/issues/8392) on macOS Catalina
=> Added CFBundleTypeRole Editor for public.directory to fix drag and drop

sources/iTermAdvancedSettingsModel.m
Fix spelling of "session" from "sesison".
=> Fix minor typo in setting description

api/library/python/iterm2/iterm2/preferences.py
a few tabs were breaking the entire `iterm2` package. `itomate` was also broken because of this
=> Fix bad indentation

sources/PseudoTerminal.m
Update the alert.informativeText for "Set Tab Title".
=> correct grammar in help text

sources/iTermTipWindowController.xib
Allow opening new window from dock when all iTerm windows are closed while 'Tip of the Day' is present, by making `iTermTipWindowController`'s window a subclass of `NSPanel`.
=> Allow new window from dock when daily tip is present.

plists/beta-iTerm2.plist, plists/iTerm2.plist, plists/iTerm2ForAppleScriptTesting-Info.plist, plists/nightly-iTerm2.plist, plists/preview-iTerm2.plist, plists/release-iTerm2.plist
Resolves https://gitlab.com/gnachman/iterm2/-/issues/10139
=> Allow requesting speech recognition permission

api/library/python/iterm2/iterm2/_version.py, api/library/python/iterm2/iterm2/filepanel.py, sources/OpenPanelBuiltInFunction.swift, sources/SavePanelBuiltInFunction.swift
1. Open the last directory by default.
2. Remove the exception if the user cancels.
=> [python API] Change the open/save panels

sources/PTYMouseHandler.m, sources/PTYSession.m, sources/VT100Output.h, tools/updateVersion.py
Handle pty mouse buttons 10 and 11
Following up on https://github.com/gnachman/iTerm2/pull/481
Fixes: https://gitlab.com/gnachman/iterm2/-/issues/10689
=> Report mouse button 10 & 11

sources/iTermSemanticHistoryController.m, sources/iTermSemanticHistoryPrefsController.h, sources/iTermSemanticHistoryPrefsController.m
Adds support opening to a file:line in Xcode IDE (using `xed` command)
=> Support opening to line number in Xcode

sources/iTermAdvancedSettingsModel.h, sources/iTermAdvancedSettingsModel.m, sources/iTermNetworkUtilization.m
Possible implementation for [Issue 11369](https://gitlab.com/gnachman/iterm2/-/issues/11369).
=> Add advanced setting to exclude utun from network utilization

sources/IntervalTree.m
I have no idea how hot this path is but I figure it can't hurt. Only spotted this because I was happy to see the Cmd-K issue resolved - thanks!
Forgive my editor for trimming trailing whitespace, if you don't want that.
=> Nit: use arrayWithCapacity initializer in fix 799afde

api/library/python/iterm2/iterm2/_version.py
to include this fix - [7e5c059](https://github.com/gnachman/iTerm2/commit/7e5c0595d93b15e0f04365a60e4b28336729b018)
=> Bump python API version
